# This is a basic workflow to help you get started with Actions

name: Testkv
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
      - uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "samplevaultja"
          secrets: '*'
        id: myGetSecretAction
